Syntax ::= StatementList

StatementList ::= (Statement ';')*

Statement ::= Print | Return | Assignement

Print ::= 'print' Returnable

Return ::= 'return' Returnable

Assignment ::= Symbol Whitespace* '=' WhiteSpace* Returnable

Returnable ::=  String | Symbol | Number | Function

String ::= '"' Char* '"'

Char ::= 'Anything thats not an unescaped doubleQuote'

Symbol ::= [a-Z] [_a-Z0-9]*

Number ::= [0-9] [0-9,]*

Function ::= '(' Symbol (Whitespace Returnable)* Whitespace* ')'

List ::= '[' (Returnable (Whitespace Returnable)*)? ']'

Whitespace ::= ('\n' | '\t' | ' ')+




